In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#sum of elements
np.sum(arr)

45

In [9]:
#mean of elements
np.mean(arr)

5.0

In [11]:
#reshaping of array
arr2=np.reshape(arr,(3,3))
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
#broadcasting function 
arr3=np.array([10,20,30,40,50,60,70,80,90])
arr3

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
arr_broad=arr+arr3

In [14]:
arr_broad

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [16]:
#vectorized multipliction
np.multiply(arr,arr_broad)

array([ 11,  44,  99, 176, 275, 396, 539, 704, 891])

In [18]:
#random number generating function
random_arr=np.random.rand(7)
print('random array',random_arr)

random array [0.11542156 0.15228787 0.80451945 0.74704059 0.48477085 0.62411224
 0.05287277]


In [19]:
#element wise comparision
arr4=np.array([1,3,4,7,9])
arr5=np.array([2,3,5,6,9])
np.equal(arr4,arr5)

array([False,  True, False, False,  True])

In [20]:
#sorting of array
arr6=np.array([1,5,4,7,9])
np.sort(arr6)

array([1, 4, 5, 7, 9])

In [ ]:
#https://numpy.org/doc/1.25/user/basics.broadcasting.html