In [2]:
import numpy as np
from scipy import integrate,interpolate,optimize,linalg,signal,stats,sparse,sqrt,sin,cos,tan,exp

In [4]:
a=sqrt(81)
a

C:\Users\asuto\AppData\Local\Temp\ipykernel_13108\1388759865.py:1: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  a=sqrt(81)


9.0

In [5]:
angle=45
sin(angle)

C:\Users\asuto\AppData\Local\Temp\ipykernel_13108\3659008272.py:2: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  sin(angle)


0.8509035245341184

In [6]:
cos(angle)

C:\Users\asuto\AppData\Local\Temp\ipykernel_13108\3779112223.py:1: DeprecationWarning: scipy.cos is deprecated and will be removed in SciPy 2.0.0, use numpy.cos instead
  cos(angle)


0.5253219888177297

In [7]:
tan(angle)

C:\Users\asuto\AppData\Local\Temp\ipykernel_13108\2199803778.py:1: DeprecationWarning: scipy.tan is deprecated and will be removed in SciPy 2.0.0, use numpy.tan instead
  tan(angle)


1.6197751905438615

In [8]:
#numerical integration
result,error=integrate.quad(lambda x:np.sin(x),0,np.pi)
result


2.0

In [11]:
#optimization
def objective(x):
    return(x-2)**2+1
b=optimize.minimize(objective,x0=0)
b.x

array([1.99999997])

In [13]:
#linear algebra
a=np.array([[1,2],[3,4]])
b=np.array([5,6])
x=linalg.solve(a,b)
x

array([-4. ,  4.5])

In [15]:
#signal processing
t=np.linspace(0,1,500)
x=np.sin(2*np.pi*5*t)+np.random.rand(t.size)*0.5
filtred=signal.medfilt(x)
filtred

array([ 3.35625348e-02,  1.28974511e-01,  2.83117776e-01,  2.83117776e-01,
        3.31254154e-01,  4.34992044e-01,  5.67072086e-01,  6.00319429e-01,
        6.86193246e-01,  6.99955210e-01,  6.99955210e-01,  8.31195040e-01,
        8.53616047e-01,  8.53616047e-01,  9.09393822e-01,  1.14775333e+00,
        1.25627209e+00,  1.25627209e+00,  1.23630571e+00,  1.23630571e+00,
        1.03747880e+00,  1.22359970e+00,  1.22359970e+00,  1.27518689e+00,
        1.27518689e+00,  1.27518689e+00,  1.22366501e+00,  1.33140064e+00,
        1.24765301e+00,  1.33140064e+00,  1.36508356e+00,  1.36508356e+00,
        1.27358828e+00,  1.27358828e+00,  1.27358828e+00,  1.17560330e+00,
        1.11278868e+00,  1.15276294e+00,  1.11278868e+00,  1.02257390e+00,
        8.88862167e-01,  8.88862167e-01,  8.88862167e-01,  5.91056986e-01,
        4.76612528e-01,  3.14612227e-01,  3.14612227e-01,  3.24224717e-01,
        3.24224717e-01,  4.61509126e-01,  3.98166350e-01,  3.98166350e-01,
        3.61439093e-01, -

In [19]:
#sparse matrces
c=sparse.csc_matrix([[1,2,5],[1,2,3],[4,3,5]])
b=sparse.csc_matrix([[1,2,0],[0,0,3],[4,0,5]])
c=c.dot(b)
c

<3x3 sparse matrix of type '<class 'numpy.intc'>'
	with 9 stored elements in Compressed Sparse Column format>

In [21]:
c.toarray()

array([[21,  2, 31],
       [13,  2, 21],
       [24,  8, 34]], dtype=int32)